
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 30 10:44:26 CET 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_BRACKET = 10;
  public static final int INCREMENT = 22;
  public static final int CONST = 5;
  public static final int EQUALS = 7;
  public static final int NOT_EQUAL = 29;
  public static final int CONTINUE = 19;
  public static final int GREATER_OR_EQUAL_THAN = 31;
  public static final int MINUS = 35;
  public static final int FOR = 21;
  public static final int DECREMENT = 23;
  public static final int GREATER_THAN = 30;
  public static final int STATIC = 14;
  public static final int SEMICOLON = 6;
  public static final int AND = 25;
  public static final int OR = 24;
  public static final int LEFT_BRACE = 3;
  public static final int CLASS = 11;
  public static final int TIMES_EQUALS = 41;
  public static final int RIGHT_PARENTHESIS = 13;
  public static final int PLUS = 34;
  public static final int IF = 16;
  public static final int BOOLEAN_CONSTANT = 50;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 28;
  public static final int LESS_OR_EQUAL_THAN = 33;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 8;
  public static final int PERCENT = 40;
  public static final int CHARACTER_CONSTANT = 48;
  public static final int RIGHT_BRACE = 4;
  public static final int BREAK = 18;
  public static final int VOID = 15;
  public static final int MINUS_EQUALS = 37;
  public static final int SOLIDUS = 39;
  public static final int PERCENT_EQUALS = 43;
  public static final int TIMES = 38;
  public static final int NUMERICAL_CONSTANT = 49;
  public static final int ELSE = 17;
  public static final int READ = 44;
  public static final int PLUS_EQUALS = 36;
  public static final int EXTENDS = 46;
  public static final int SOLIDUS_EQUALS = 42;
  public static final int LESS_THAN = 32;
  public static final int LEFT_BRACKET = 9;
  public static final int PRINT = 45;
  public static final int LEFT_PARENTHESIS = 12;
  public static final int IDENTIFIER = 47;
}

